# Generated by Django 3.0.6 on 2020-08-18 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amplicon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplicon_name', models.CharField(max_length=100)),
                ('exon', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['analysis_type'],
            },
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=50)),
                ('chromosome', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Imported_By',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_by', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('current', 'current'), ('ex', 'ex')], default='current', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Primer_Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_set', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=150)),
                ('sequence', models.TextField(max_length=150)),
                ('genomic_location_start', models.IntegerField(blank=True, null=True)),
                ('genomic_location_end', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('direction', models.CharField(max_length=5)),
                ('alt_name', models.TextField(blank=True, max_length=255, null=True)),
                ('ngs_audit_number', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_imported', models.CharField(blank=True, max_length=20, null=True)),
                ('version', models.IntegerField(blank=True, default='1')),
                ('modification', models.CharField(blank=True, choices=[('HEX', 'HEX'), ('6FAM', '6FAM'), ('5FAM', '5FAM'), ('TAM', 'TAM'), ('BIOTIN', 'BIOTIN'), ('', '')], default='', max_length=10, null=True)),
                ('modification_5', models.CharField(blank=True, choices=[('HEX', 'HEX'), ('6FAM', '6FAM'), ('5FAM', '5FAM'), ('TAM', 'TAM'), ('BIOTIN', 'BIOTIN'), ('', '')], default='', max_length=10, null=True)),
                ('order_status', models.CharField(choices=[('Stocked', 'Stocked'), ('Ordered', 'Ordered'), ('Order Placed', 'Order Placed'), ('Recieved', 'Recieved'), ('In Testing Sanger', 'In Testing Sanger'), ('In Testing Non-Sanger', 'In Testing Non-Sanger'), ('Failed Validation', 'Failed Validation'), ('Archived', 'Archived')], default='Stocked', max_length=50)),
                ('reason_archived', models.CharField(blank=True, max_length=1000, null=True)),
                ('date_archived', models.CharField(blank=True, max_length=20, null=True)),
                ('date_order_placed', models.CharField(blank=True, max_length=20, null=True)),
                ('date_order_recieved', models.CharField(blank=True, max_length=20, null=True)),
                ('date_testing_completed', models.CharField(blank=True, max_length=20, null=True)),
                ('date_retesting_completed', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_ordered', models.CharField(choices=[('Repeat order', 'Repeat order'), ('New gene / version', 'New gene / version'), ('NGS confirmation', 'NGS confirmation'), ('Scientist R&D', 'Scientist - R&D'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=100)),
                ('m13_tag', models.CharField(choices=[('GTAAAACGACGGCCAGT', 'GTAAAACGACGGCCAGT'), ('CAGGAAACAGCTATGAC', 'CAGGAAACAGCTATGAC'), ('None', 'None')], default='None', max_length=20)),
                ('worksheet_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('amplicon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primer_db_site.Amplicon')),
                ('archived_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_by', to='primer_db_site.Imported_By')),
                ('imported_by_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primer_db_site.Imported_By')),
            ],
        ),
        migrations.AddField(
            model_name='amplicon',
            name='analysis_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primer_db_site.Analysis_Type'),
        ),
        migrations.AddField(
            model_name='amplicon',
            name='gene_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primer_db_site.Gene'),
        ),
        migrations.AddField(
            model_name='amplicon',
            name='primer_set_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primer_db_site.Primer_Set'),
        ),
    ]
