# Generated by Django 3.0.6 on 2020-08-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='modification',
            field=models.CharField(blank=True, choices=[('HEX', 'HEX'), ('6FAM', '6FAM'), ('5FAM', '5FAM'), ('TAM', 'TAM'), ('BIOTIN', 'BIOTIN'), ('', '')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='primer',
            name='modification_5',
            field=models.CharField(blank=True, choices=[('HEX', 'HEX'), ('6FAM', '6FAM'), ('5FAM', '5FAM'), ('TAM', 'TAM'), ('BIOTIN', 'BIOTIN'), ('', '')], max_length=10, null=True),
        ),
    ]
