# Generated by Django 2.2.6 on 2020-01-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0002_auto_20191220_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='order_status',
            field=models.CharField(default='Stocked', max_length=50),
        ),
    ]
