# Generated by Django 2.2.6 on 2020-01-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0003_primer_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='version',
            field=models.IntegerField(blank=True, default='1'),
        ),
    ]
