# Generated by Django 2.2.6 on 2020-01-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0004_primer_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='order_status',
            field=models.CharField(choices=[('Stocked', 'Stocked'), ('Ordered', 'Ordered'), ('Archived', 'Archived')], default='Stocked', max_length=50),
        ),
    ]
