# Generated by Django 2.1 on 2020-01-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0008_auto_20200118_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='order_status',
            field=models.CharField(choices=[('Stocked', 'Stocked'), ('Ordered', 'Ordered'), ('Order Placed', 'Order Placed'), ('Recieved', 'Recieved'), ('In Testing', 'In Testing'), ('Failed Validation', 'Failed Validation'), ('Archived', 'Archived')], default='Stocked', max_length=50),
        ),
    ]
