# Generated by Django 2.1 on 2020-01-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0009_auto_20200118_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='date_order_placed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
