# Generated by Django 2.1 on 2020-01-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0010_primer_date_order_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='date_order_recieved',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
