# Generated by Django 2.1 on 2020-01-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0011_primer_date_order_recieved'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='date_testing_completed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
