# Generated by Django 2.1 on 2020-05-11 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0012_primer_date_testing_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='imported_by',
            name='status',
            field=models.CharField(choices=[('current', 'current'), ('ex', 'ex')], default='current', max_length=10),
        ),
        migrations.AddField(
            model_name='primer',
            name='modification',
            field=models.CharField(choices=[('HEX', 'HEX'), ('6FAM', '6FAM'), ('5FAM', '5FAM'), ('TAM', 'TAM'), ('BIOTIN', 'BIOTIN'), ('None', 'None')], default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='primer',
            name='reason_reordered',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='primer',
            name='archived_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_by', to='primer_db_site.Imported_By'),
        ),
        migrations.AlterField(
            model_name='primer',
            name='imported_by_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='primer_db_site.Imported_By'),
        ),
    ]
