# Generated by Django 3.0.6 on 2020-08-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0013_auto_20200511_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primer',
            name='reason_reordered',
        ),
        migrations.AddField(
            model_name='primer',
            name='date_retesting_completed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='primer',
            name='m13_tag',
            field=models.CharField(choices=[('GTAAAACGACGGCCAGT', 'GTAAAACGACGGCCAGT'), ('CAGGAAACAGCTATGAC', 'CAGGAAACAGCTATGAC'), ('', '')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='primer',
            name='name',
            field=models.TextField(default='Unnamed', max_length=150),
        ),
        migrations.AddField(
            model_name='primer',
            name='reason_ordered',
            field=models.CharField(choices=[('Repeat order', 'Repeat order'), ('New gene / version', 'New gene / version'), ('NGS confirmation', 'NGS confirmation'), ('Scientist R&D', 'Scientist - R&D'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
