# Generated by Django 3.0.6 on 2020-06-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0013_auto_20200511_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='date_retesting_completed',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
