# Generated by Django 3.0.6 on 2020-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0014_primer_date_retesting_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='reason_for_order',
            field=models.CharField(choices=[('Repeat order', 'Repeat order'), ('New gene / version', 'New gene / version'), ('NGS confirmation', 'NGS confirmation'), ('Scientist R&D', 'Scientist - R&D'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
