# Generated by Django 3.0.6 on 2020-08-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0014_auto_20200803_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='order_status',
            field=models.CharField(choices=[('Stocked', 'Stocked'), ('Ordered', 'Ordered'), ('Order Placed', 'Order Placed'), ('Recieved', 'Recieved'), ('In Testing Sanger', 'In Testing Sanger'), ('In Testing Non-Sanger', 'In Testing Non-Sanger'), ('Failed Validation', 'Failed Validation'), ('Archived', 'Archived')], default='Stocked', max_length=50),
        ),
    ]
