# Generated by Django 3.0.6 on 2020-06-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0015_primer_reason_for_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primer',
            old_name='reason_for_order',
            new_name='reason_ordered',
        ),
        migrations.RemoveField(
            model_name='primer',
            name='reason_reordered',
        ),
    ]
