# Generated by Django 3.0.6 on 2020-08-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0015_auto_20200804_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='worksheet_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
