# Generated by Django 3.0.6 on 2020-08-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0016_primer_worksheet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='m13_tag',
            field=models.CharField(choices=[('GTAAAACGACGGCCAGT', 'GTAAAACGACGGCCAGT'), ('CAGGAAACAGCTATGAC', 'CAGGAAACAGCTATGAC'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
