# Generated by Django 3.0.6 on 2020-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0016_auto_20200611_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='name',
            field=models.TextField(default='Unnamed', max_length=150),
        ),
    ]
