# Generated by Django 3.0.6 on 2020-08-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0017_auto_20200810_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primer',
            name='modification',
            field=models.CharField(choices=[('HEX', 'HEX'), ('6FAM', '6FAM'), ('5FAM', '5FAM'), ('TAM', 'TAM'), ('BIOTIN', 'BIOTIN'), ('', '')], default='', max_length=10),
        ),
    ]
