# Generated by Django 3.0.6 on 2020-08-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_db_site', '0018_auto_20200813_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='primer',
            name='modification_5',
            field=models.CharField(choices=[('HEX', 'HEX'), ('6FAM', '6FAM'), ('5FAM', '5FAM'), ('TAM', 'TAM'), ('BIOTIN', 'BIOTIN'), ('', '')], default='', max_length=10),
        ),
    ]
